#  ████████╗██╗██╗░░░░░░█████╗░░█████╗░██╗░░██╗
#  ╚══██╔══╝██║██║░░░░░██╔══██╗██╔══██╗██║░██╔╝
#  ░░░██║░░░██║██║░░░░░██║░░██║██║░░██║█████═╝░
#  ░░░██║░░░██║██║░░░░░██║░░██║██║░░██║██╔═██╗░
#  ░░░██║░░░██║███████╗╚█████╔╝╚█████╔╝██║░╚██╗
#  ░░░╚═╝░░░╚═╝╚══════╝░╚════╝░░╚════╝░╚═╝░░╚═╝
# Creator plugin TiLock, если вам понравился плагин, оставьте, пожалуйста, отзыв на spigotmc.ru
# Буду очень благодарен!
# Ds: https://discord.gg/yQ58jzNyZ6
# Tg: https://t.me/TILockPezherka

# LockShulkerX, By TILock, CreatorPlugin Timofe2929, Offical LockShulkerX, Спасибо что используете!

# К сожелению это последние обновление

shulkers:
  level-1:
    name: "&cШалкер I уровня" # Название шалкера зависимо от уровня
    description:
      - "&7Чем дальше в лес " #Описания шалкера
      - "&7Тем" #Описания шалкера
      - "&7Скибиди доп ес ес" #Описания шалкера
    panel_name: "&bПанель I уровня" # Название панели
  level-2:
    name: "&bШалкер II уровня" # Название шалкера зависимо от уровня
    description:
      - "&7Але петя!" #Описания шалкера
      - "&7Что такое" #Описания шалкера
      - "&7Я упала" #Описания шалкера
    panel_name: "&bПанель II уровня" #Название панели
  level-3:
    name: "&bШалкер III уровня" # Название шалкера зависимо от уровня
    description:
      - "&7Уго такой уровень" #Описания шалкера
      - "&7Поднялся сто проц" #Описания шалкера
      - "&7Согласен" #Описания шалкера
    panel_name: "&bПанель III уровня" #Название панели
  level-4:
    name: "&bШалкер IV уровня" # Название шалкера зависимо от уровня
    description:
      - "&7Ура макс левл" #Описания шалкера
      - "&7Юху" #Описания шалкера
      - "&7Я крутой!" #Описания шалкера
    panel_name: "&bПанель IV уровня" #Название панели

settings:
  shulker-open-delay: 5  # Задержка в секундах при повторном открытии шалкера
  shulker-panel-material: "LIGHT_BLUE_STAINED_GLASS_PANE" # Цвет панелей которые находятся в шалкере 1, 2, 3 уровня
  shulker-barrier-material: "BARRIER" #Материал при открытье шалкера
  require-permission-to-open-air: true  # Работает ли пермишон? permission (lockshulker.open.air)
  shulker-barrier-name: "&cБарьер" #Название данного материала
  shulker-open-sound: "minecraft:block.shulker_box.open" # Звук когда открыл шалкер
  shulker-close-sound: "minecraft:block.shulker_box.close" # Звук когда закрыл шалкер
  panel-name: '&bLockHub' #Название панели когда шалкер открыт
  items-pickup: # предметы которые шалкер будет подбирать
    - DIAMOND_HELMET
    - GOLDEN_APPLE
    - IRON_SWORD
  pickup-sound: #Звук когда подобрал предмет
    name: ENTITY_ITEM_PICKUP
    volume: 1.0
    pitch: 1.0

messages:
  max-shulker-reached: "&cВы не можете хранить более %max% шалкеров в инвентаре!" #Сообщение о том что перевысили лимит шалкеров
  shulker-dropped: "&eВаши лишние шалкеры были выброшены на землю при выходе с сервера." #Сообщение о том что шалкера были выброшини про выходи с сервера
  cannot-place-in-chest: "&cНельзя класть шалкеры в сундуки!" #Сообщение о том что не льзя класть шалкера в сундук и тд.
  reload-success: "&aКонфигурация плагина LockShulker перезагружена!" #Сообщение о том что конфигурация перезагружена
  no-permission: "&cУ вас нет прав для выполнения этой команды." #Нет прав
  no-permission-air: "&cУ вас нет прав для открытия шалкера в воздухе." # Если нет пермишона пишет это

